generator:
  class: sfDoctrineGenerator
  param:
    model_class:           mdNewsletterTemplate
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          md_newsletter_template
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: { label: Nombre }
        subject: { label: Subject }
        created_at: { label: Fecha de Creacion, date_format: dd/MM/yyyy HH:mm }
      list:
        object_actions:
          _delete: ~
          _edit:   ~
          _encolar:   { name: encolar, action: encolar, params: { class: 'template_encolar' } }
          _preview:   { name: preview, action: preview, params: { class: 'iframe' } }
        display: [name, subject, created_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
