<?php

/**
 * PluginmdNewsletterGroupSubscriberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsletterGroupSubscriberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsletterGroupSubscriberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsletterGroupSubscriber');
    }

    public function findByKeys($values){
    	return  mdNewsletterGroupSubscriberTable::getInstance()->findBymd_subscriber_idAndMd_group_id($values['md_subscriber_id'], $values['md_group_id']);
    }


}