<?php

/**
 * PluginmdNewsletterLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsletterLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsletterLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsletterLog');
    }
}