<?php

/**
 * PluginmdNewsletterLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdNewsletterLog extends BasemdNewsletterLog
{
  public static function log($code, $message, $md_queue_id = NULL, $md_subscriber_id = NULL){
    $log = new mdNewsletterLog();
    if(!is_null($md_queue_id))
      $log->setMdQueueId($md_queue_id);
    
    if(!is_null($md_subscriber_id))
      $log->setMdSubscriberId($md_subscriber_id);
    
    $log->setProblemErrorCode((string)$code);
    $log->setProblemErrorText($message);
    $log->save();
  }
}