<?php

/**
 * PluginmdNewsletterQueueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsletterQueueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsletterQueueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsletterQueue');
    }
    public function findScheduleToSend(){
      $q = $this->createQuery('q')
            ->where("q.status not in ('cancelled', 'sent')")
            ->andWhere("q.sending_date <= '" . date('Y-m-d H:i:s', time()) . "'");
      return $q->fetchOne();
    }
}