<?php

/**
 * PluginmdNewsletterGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsletterGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsletterGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsletterGroup');
    }


    public function findByKeys($values){
    	return  mdNewsletterGroupSubscriberTable::getInstance()->findBymd_subscriber_idAndMd_group_id($values['md_subscriber_id'], $values['md_group_id']);
    }
}