<?php

/**
 * PluginmdNewsletterTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsletterTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsletterTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsletterTemplate');
    }
}