all:
  mdNewsletter2DoctrinePlugin:
    templates:
      # Normal: 'mdNewsletterTemplate'
      # Campaña: 'mdFirstTemplate'

  observer:
    taskSymfonyUrl: http://symfony/
    taskFrontendUrl: http://www.example.tld/

# Nombre de dominio sin http:// usado para colocar links en los templates de newsletter
  domain:
    url: www.example.tld